### ISSUE TITLE
feature - Implement OpenAPI generation support

### ISSUE THREAD

**Issue by itsthedevman** [itsthedevman/spec_forge#23]
# Feature Description

Add automatic OpenAPI documentation generation to SpecForge, allowing users to generate OpenAPI 3.0 specification files based on their existing tests with minimal additional configuration.

# Use Case

API developers want to maintain accurate and up-to-date API documentation without duplicating effort. Since SpecForge tests already define endpoints, parameters, request bodies, and expected responses, they contain most of the information needed for API documentation. By generating OpenAPI specifications from these tests, developers can:

1. Keep documentation in sync with actual API behavior
2. Avoid the tedious work of manually writing OpenAPI specs
3. Leverage existing test definitions to bootstrap documentation
4. Use the generated OpenAPI files with tools like Swagger UI, Redoc, or code generators

# Proposed Solution

Implement a dual approach that automatically extracts as much information as possible from tests while providing a clean configuration system for additional metadata:

## 1. Command-line interface:

```bash
# Generate OpenAPI spec from all tests
spec_forge generate openapi

# Generate and save to specific file (format auto-detected from extension)
spec_forge generate openapi --output api-docs.yml

# Generate and save with specific format 
spec_forge generate openapi --output api-docs --format json

# Continue despite documentation warnings
spec_forge generate openapi --ignore-warnings

# Preview the documentation in a browser
spec_forge docs serve

# Preview with a specific renderer
spec_forge docs serve --renderer redoc
spec_forge docs serve --renderer swagger
```

## 2. File structure for configuration:

```
spec_forge/
  openapi/               # OpenAPI specific configs
    openapi.yml          # Main API metadata
    schemas/             # Schema definitions
      user.yml
      post.yml
      comment.yml
```

## 3. Configuration in forge_helper.rb:

```ruby
SpecForge.configure do |config|
  # OpenAPI generation options
  config.openapi.output = "openapi.yml" # Output file
  config.openapi.version = "3.0"   # OpenAPI version
end
```

## 4. Architecture Components:

The implementation will follow a clean architecture with these key components:

- **Loader**: Extracts raw API information from SpecForge tests
- **Builder**: Processes and organizes that information
- **Document**: Represents the API documentation in a version-agnostic way
- **Renderer**: Transforms the document to specific output formats

This modular approach allows for future extension to other documentation formats beyond OpenAPI.

## 5. In-test Documentation:

Tests can include additional OpenAPI documentation via a dedicated section:

```yaml
create_user:
  path: /users
  method: POST
  openapi:
    summary: Create a new user account 
    description: Creates a user account with the provided details
    tags: [users, accounts]
  body:
    name: string
    email: string
  expectations:
  - expect:
      status: 201
```

## 6. Configuration in openapi.yml:

For API metadata that can't be extracted from tests:

```yaml
info:
  title: My Awesome API
  version: 1.0.0
  description: A comprehensive API for managing things
  contact:
    name: API Team
    email: api@example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://api.example.com/v1
    description: Production
  - url: https://staging-api.example.com/v1
    description: Staging

tags:
  users:
    description: User management
  posts:
    description: Post management
  
security_schemes:
  bearer_auth:
    type: http
    scheme: bearer
    bearer_format: JWT
```

## 7. Simplified Schema Format:

A key feature of this implementation is a dramatically simplified schema format that feels natural to Ruby developers while maintaining full OpenAPI compatibility:

```yaml
# schemas/user.yml - Simplified SpecForge format
properties:
  # Direct type assignments (no nested type:)
  id: integer
  name: string
  
  # Format names used directly as types
  email: email
  created_at: datetime
  user_id: uuid
  
  # Type inference from constraints
  username:
    min_length: 3
    max_length: 20
    pattern: "^[a-zA-Z0-9_-]+$"
  
  # Enums with type inference
  role:
    enum:
      - admin
      - user
      - guest
    description: "User's role in the system"
  
  # Object nesting with simplified syntax
  address:
    properties:
      street: string
      city: string
      zip: string
    required:
      - street
      - city
  
  # Arrays with simplified syntax
  tags:
    items: string
    
  # Reference to another schema
  posts:
    items: "#/components/schemas/Post"

# Snake_case options for all camelCase properties
required:
  - id
  - name
  - email
```

# Alternatives Considered

1. **Full OpenAPI in YAML annotations** - Requiring users to add full OpenAPI annotations to their test files, but this would make tests more verbose and harder to maintain.
    
2. **Completely automatic generation** - Generating OpenAPI specs with no additional configuration, but this would limit the quality and completeness of the documentation.
    
3. **Separate documentation system** - Creating a completely separate documentation system, but this would lose the benefit of keeping tests and docs in sync.
