### ISSUE TITLE
feature - Implement a negated matcher

### ISSUE THREAD

**Issue by itsthedevman** [itsthedevman/spec_forge#25]
## Feature Description
Sometimes you need to check if something is not something else. Or maybe you feel that SpecForge is incomplete until it can `not_to` instead of `to`. This feature request would like to make those dreams into reality. 

## Proposed Solution

I propose adding a new `matcher.not` matcher into SpecForge. Similar to `matcher.and` in usage and implementation. Instead of fighting RSpec's `not_to` and `to` for the various use cases and edge cases, it is easier to implement a RSpec custom matcher that negates the result for us. 

So instead of:
```rb
expect(name).not_to eq("bob")
```
We do this:
```rb
expect(name).to negate(eq("bob"))
```

Though in the example I used `negate`,  I would name this custom matcher `forge_not` to be consistent and avoid conflicts.

## Example Usage

```yaml
# Simple 
matcher.not: "bob"
# forge_not(eq("bob"))

# Supports other matchers
matcher.not: 
  matcher.end_with: ".net"
# forge_not(end_with(".net"))

# And compound matchers
matcher.not:
  matcher.and: 
  - matcher.end_with: ".net"
  - matcher.end_with: ".com"
# forge_not(forge_and(end_with(".net"), end_with(".com")))

# It can also be used as arguments for other matchers
matcher.and:
- matcher.start_with: "b"
- matcher.not: "bob"
# forge_and(start_with("b"), forge_not(eq("bob")))
```

## Alternatives Considered
Yes - but this is da only wae
