### ISSUE TITLE
feature - Implement an "or" matcher

### ISSUE THREAD

**Issue by itsthedevman** [itsthedevman/spec_forge#27]
## Feature Description
To complete the trifecta of custom matchers for SpecForge, it would be good to have a way to match to a value anything in a list of items. 

## Use Case

This would allow people to be able to more dynamically handle testing results, such as enums, where it could be one of n values. It can also make generic tests to be more specific. 

For example, 
```yaml
json:
  access_level: kind_of.string
```
Could become:
```yaml
json:
  access_level: 
    matcher.or:
    - "guest"
    - "standard"
```

## Proposed Solution

I imagine this will be a custom matcher just like its fellow kin.  Named `matcher.or` in yaml and registered as `forge_or` with RSpec. 

## Example Usage

```yaml
json:
  access_level: 
    matcher.or:
    - "guest"
    - "standard"
```

## Alternatives Considered
Yes, it requires writing generic tests, multiple tests, or using certain matchers to mimic
