### ISSUE TITLE
feature - Allow `Context::Store::Entry` to be modifiable by callbacks

### ISSUE THREAD

**Issue by itsthedevman** [itsthedevman/spec_forge#28]
## Feature Description

When I originally implemented `Context::Store::Entry`, I designed the class to use Data and a rigid structure. However, after working on the wiki documentation, I realized that I accidentally locked users out of some useful advanced functionality with that choice. 

This proposed change would turn `Context::Store::Entry` into a dynamic class capable of accepting any structure provided - allowing users to set data via callbacks and accessing that data in the tests.

## Use Case

When testing complex APIs, developers may need to store and manipulate custom data between tests that doesn't naturally fit into the existing request/response structure. 

## Example Usage

```rb
SpecForge.configure do |config|
  config.register_callback(:setup_test_data) do |context|
    SpecForge.context.store.set(
      "app_config", 
      secret_key: "yarr-my-secrets",
      api_version: "2.0"
    )

    SpecForge.context.store.set(
      "test_ids",
      admin_user: 1001,
      regular_user: 1002
    )
  end
end
```

Then in YAML tests:

```yaml
global:
  callbacks:
  - before_file: setup_test_data

get_user:
  path: "/users/{id}"
  query:
    id: store.test_ids.admin_user
  headers:
    X-API-Version: store.app_config.api_version
  expectations:
  - expect:
      status: 200
```

## Alternatives Considered

N/A

## Additional Context

No
