### ISSUE TITLE
feature - Add support for spec dependencies via `relies_on` attribute

### ISSUE THREAD

**Issue by itsthedevman** [itsthedevman/spec_forge#29]
## Feature Description

Add support for explicit test dependencies through a `relies_on` attribute, allowing tests that depend on state from previous tests to run correctly even when executed in isolation.

## Use Case

When testing API workflows (like authentication flows, multi-step CRUD operations, etc.), tests often depend on state created by previous tests. Currently, these tests work when run as a complete file but may fail when run individually because everything isn't in the correct state.  

## Proposed Solution

Add a `relies_on` attribute at the spec level that can specify dependencies:

```yaml
create_user:
  path: /users
  method: post
  # Test details...

get_user:
  relies_on: create_user
  path: /users/{id}
  # Test details...

update_user:
  relies_on: # Support for multiple dependencies
  - create_user
  - get_user  
  path: /users/{id}
  method: patch
  # Test details...
```

When someone runs `update_user` directly, SpecForge would first run `create_user` and `get_user` to establish the necessary state.

## Example Usage

```yaml
# Authentication flow example
login:
  path: "/auth/login"
  method: post
  body:
    email: "user@example.com"
    password: "password123"
  store_as: auth
  expectations:
  - expect:
      status: 200
      json:
        token: kind_of.string

get_profile:
  relies_on: login  # This test needs login to run first
  path: "/profile"
  headers:
    Authorization:
      transform.join:
      - "Bearer "
      - store.auth.body.token
  expectations:
  - expect:
      status: 200

logout:
  relies_on: # This test needs both previous tests
  - login
  - get_profile  
  path: "/auth/logout"
  method: post
  headers:
    Authorization:
      transform.join:
      - "Bearer "
      - store.auth.body.token
  expectations:
  - expect:
      status: 200
```

## Alternatives Considered

Dis is da wae
