### ISSUE TITLE
feature - Add user-facing descriptions to normalizer attributes

### ISSUE THREAD

**Issue by itsthedevman** [itsthedevman/spec_forge#42]
## Feature Description

Add support for `description` and `examples` fields in normalizer structure definitions to provide user-facing documentation and enhanced error messages.

## Use Case

Currently, when users encounter validation errors, they get technical type information but no context about what the attribute actually does or how to use it properly. This feature would:

1. **Improve error messages** - Include helpful descriptions when validation fails
2. **Serve as documentation** - Provide in-code documentation for developers
3. **Guide users** - Give examples of valid values right in the error message

### Structure Definition Enhancement

Update normalizer structure definitions to support an optional `description` field:

```yaml
http_verb:
  type: string
  default: null
  required: false
  aliases:
    - method
    - http_method
  validator: http_verb
  description: |-
    The HTTP method to use for the request. Common methods include GET for 
    retrieving data, POST for creating resources, and DELETE for removing resources.
    
    Examples: "GET", "POST", "PATCH", "DELETE"
```

### Enhanced Error Messages

Transform current error output from:
```
Invalid HTTP verb "INVALID" for "http_verb" in user spec. Valid values are: "GET", "POST", "PUT", "PATCH", "DELETE"
```

To something like:
```
Invalid HTTP verb "INVALID" for "http_verb" in user spec:
  Expected: String matching one of ["GET", "POST", "PUT", "PATCH", "DELETE"]
  Got: "INVALID"

About http_verb:
  The HTTP method to use for the request. Common methods include GET for 
  retrieving data, POST for creating resources, and DELETE for removing resources.
  
  Examples: "GET", "POST", "PATCH", "DELETE"
```

## Example Usage

Users would get much more helpful error messages that explain not just what's wrong, but what the field is for and how to fix it. This is especially valuable for newcomers to SpecForge who might not understand the purpose of each configuration option.
